### ISSUE TITLE
Setting up PORO for updating the database

### ISSUE THREAD

**Issue by julsfelic** [nrel-market-mapper/nrel-market-mapper#2]
Using the service PORO populate the installs table with relevant data

**Comment by julsfelic** [comment]
Add a hidden route that updates our database with the most recent API data

**Comment by julsfelic** [comment]
Make note that we can only hit the API 1000 times an hour. Get a small smaple working before a full on test.

**Comment by ksk5280** [comment]
I'm closing this issue because we decided to seed and update the database using a rake task instead
